# Generated by Django 4.2.5 on 2023-09-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_cake'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_image'),
        ),
    ]
