# Generated by Django 4.2.5 on 2023-09-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_cake_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='item_image'),
        ),
        migrations.AddField(
            model_name='cake',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='item_image'),
        ),
        migrations.AddField(
            model_name='cake',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='item_image'),
        ),
    ]
