# Generated by Django 4.2.5 on 2023-09-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0004_cake_image1_cake_image2_cake_image3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('emailaddress', models.CharField(max_length=100)),
                ('phonenumber', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
